//
//  ExpandableModels.swift
//  ARExpandableCell
//
//  Created by Antony Raphel on 09/01/19.
//  Copyright (c) 2019 Antony Raphel. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SectionType {
    case iPhone
    case iPad
    case mac
    case watch
    case tv
}

enum Title: String {
    case iPhone = "iPhone"
    case iPad = "iPad"
    case mac = "Mac"
    case watch = "Watch"
    case tv = "Tv"
}

enum Expandable {
    // MARK: Use cases
    
    enum Initial {
        struct Request {
        }
        struct Response {
            struct ProductResponse {
                struct AppleProductResponse {
                    var title: String
                }
                var state: Bool
                var type: SectionType
                var title: String
                var products: [AppleProductResponse]
            }
            var summary: [ProductResponse]
        }
        struct ViewModel {
            struct ProductViewModel {
                struct AppleProductViewModel {
                    var title: String
                }
                var state: Bool
                var type: SectionType
                var title: String
                var products: [AppleProductViewModel]
            }
            var summary: [ProductViewModel]
        }
    }
    
    enum Update {
        struct Request {
            var state: Bool
            var type: SectionType
        }
    }
}
